# Make file for Win32
#
# (c) 2004-2010 Denora Team
# Contact us at info@denorastats.org
#
# Please read COPYING and README for further details.
#
# Based on the original code of Anope by Anope Team.
# Based on the original code of Thales by Lucas.
#
# $Id$
#

###########################################################################

clean: 
	-@erase language.h

spotless: clean
	-@erase sysconf.h version.h

distclean: spotless

FRC:
